<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Banquinho.Application\Banquinho.Application.csproj" />
    <ProjectReference Include="..\Banquinho.Domain\Banquinho.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repository\" />
  </ItemGroup>

</Project>
